language: node_js

node_js:
  - '5'
  - '6'

branches:
  - master

script:
  - ls -al build/css/feathericon.css
  - ls -al build/css/feathericon.min.css
  - ls -al build/fonts/feathericon.eot
  - ls -al build/fonts/feathericon.svg
  - ls -al build/fonts/feathericon.ttf
  - ls -al build/fonts/feathericon.woff
  - ls -al build/fonts/feathericon.woff2
  - ls -al build/scss/_feathericon.scss
  - ls -al build/svg/sprite.feathericon.svg

deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_API_KEY}
  skip_cleanup: true
  on:
    branch: master
    repo: ${TRAVIS_REPO_SLUG}
